/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.OpenDeAustralia;
import logica.Partido;

/**
 *
 * @author Shonny
 */
public class VentanaVerRondas extends javax.swing.JFrame {

    private OpenDeAustralia miOpenAustralia;

    /**
     * Creates new form VentanaVerRondas
     */
    public VentanaVerRondas(OpenDeAustralia open) {
        miOpenAustralia = open;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/interfaz/images/logo.png")).getImage());
        //************************
        //Centrar Jframe
        setLocationRelativeTo(null);
        //************************
        llenarTablaOctavos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVerRondas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Octavos de Final");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Partidos"));

        jTableVerRondas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Hora y Fecha", "Jugador 1", "Jugador 2", "Pista"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVerRondas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableVerRondas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVerRondasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVerRondas);
        if (jTableVerRondas.getColumnModel().getColumnCount() > 0) {
            jTableVerRondas.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTableVerRondas.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableVerRondasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVerRondasMouseClicked
        // TODO add your handling code here:
        VentanaJugarPartido partido = new VentanaJugarPartido(miOpenAustralia);
        int filSelec;
        String id;
        filSelec = jTableVerRondas.getSelectedRow();
        if (evt.getClickCount() == 2 && filSelec != -1) {
            //obtengo el los datos de la columna 0
            id = jTableVerRondas.getValueAt(filSelec, 0).toString();
            VentanaJugarPartido.idPartido = id;
            System.out.println(VentanaJugarPartido.idPartido);
            partido.inicializarDatosVentanaPartido();

            partido.setVisible(true);
        }
    }//GEN-LAST:event_jTableVerRondasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVerRondas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVerRondas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVerRondas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVerRondas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVerRondas(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVerRondas;
    // End of variables declaration//GEN-END:variables

    public void llenarTablaOctavos() {
        DefaultTableModel dtm = (DefaultTableModel) jTableVerRondas.getModel();//se usa DefaultTableModel para manipular facilmente el Tablemodel
        dtm.setRowCount(0);//eliminando la s filas que ya hay. para agregar desde el principio.
        //los datos se agregan la defaultTableModel.
        ArrayList<Partido> octavos = miOpenAustralia.getOctavos();//sacando al informacion a agregar en la tabla.

        //como se va a llenar una tabla de 5 columnas, se crea un vector de 3 elementos.
        //se usa un arreglo de Object para poder agregar a la tabla cualquier tipo de datos.
        Object[] datos = new Object[5];

        for (int i = 0; i < octavos.size(); i++) {

            Partido octa = octavos.get(i);
            //Se agrega este if para evitar que el extraiga datos en un campo null
            if (octa != null) {

                datos[0] = octa.getId();
                datos[1] = octa.getFechaHora();//el primer elemetno del arreglo va a ser el id,la primera col en la Tabla.
                datos[2] = octa.getJugador1().getNombre();
                datos[3] = octa.getJugador2().getNombre();
                datos[4] = octa.getPista().getNombre();

                //agrego al TableModleo ese arreglo
                dtm.addRow(datos);
            }
        }
        //metodo que modifica las celdas de la tabla
//        dtm.addTableModelListener(new TableModelListener() {
//            //metodo que verifica si existe un cambio en la tabla
//            @Override
//            public void tableChanged(TableModelEvent e) {
//                //if que verifica si existe cambio
//                if (e.getType() == TableModelEvent.UPDATE) {
//                    //se obtiene la columna en la cual se modifico la celda
//                    int columna = e.getColumn();
//                    //se obtiene la fila en la cual se modifico la celda
//                    int fila = e.getFirstRow();
//                    //se obtiene el id del jugador de la fila seleccionada 
//                    String id = jTablePista.getValueAt(fila, 0).toString();
//                    //se obtiene el elemento modificado
//                    String dato = jTablePista.getValueAt(fila, columna).toString();
//
//                    miOpenAustralia.modificarPista(id, dato, columna);
//                }
//            }
//        });
        //**************************************************
    }
}
