/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.KeyEvent;
import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import logica.*;

/**
 *
 * @author Shonny
 */
public class VentanaAgregarJugador extends javax.swing.JFrame {

    private OpenDeAustralia miOpenAustralia;
    private Jugador miJugador;

    /**
     * Creates new form VentanaAgregarJugador
     */
    public VentanaAgregarJugador(OpenDeAustralia open) {
        miOpenAustralia = open;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/interfaz/images/logo.png")).getImage());

        //************************
        //Centrar Jframe
        setLocationRelativeTo(null);
        //************************
        llenarTablaJugador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTidJugador = new javax.swing.JTextField();
        jTnombreJugador = new javax.swing.JTextField();
        jTrankingJugador = new javax.swing.JTextField();
        jTedadJugador = new javax.swing.JTextField();
        jBagregarJugador = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJugadores = new javax.swing.JTable();
        jBborrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Jugador");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Jugador"));

        jLabel1.setText("Id:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Ranking ATP:");

        jLabel4.setText("Edad:");

        jTidJugador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTidJugadorKeyTyped(evt);
            }
        });

        jTnombreJugador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnombreJugadorKeyTyped(evt);
            }
        });

        jTrankingJugador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTrankingJugadorKeyTyped(evt);
            }
        });

        jTedadJugador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTedadJugadorKeyTyped(evt);
            }
        });

        jBagregarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/images/agregar16.png"))); // NOI18N
        jBagregarJugador.setText("Agregar");
        jBagregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBagregarJugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTnombreJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jTidJugador)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTrankingJugador)
                            .addComponent(jTedadJugador))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTidJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTnombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTedadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTrankingJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBagregarJugador)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Jugadores"));

        jTableJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Edad", "Puntos ATP", "Ranking ATP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableJugadores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableJugadores);
        if (jTableJugadores.getColumnModel().getColumnCount() > 0) {
            jTableJugadores.getColumnModel().getColumn(0).setResizable(false);
            jTableJugadores.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableJugadores.getColumnModel().getColumn(1).setResizable(false);
            jTableJugadores.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTableJugadores.getColumnModel().getColumn(2).setResizable(false);
            jTableJugadores.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTableJugadores.getColumnModel().getColumn(3).setResizable(false);
            jTableJugadores.getColumnModel().getColumn(4).setResizable(false);
        }

        jBborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/images/borrar16.png"))); // NOI18N
        jBborrar.setText("Borrar");
        jBborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(jBborrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBborrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBagregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarJugadorActionPerformed
        // TODO add your handling code here:
        //validar datos
        if (ValidarDatosAgregarJugador().equals("")) {

            //Obtenemos los datos de los campos de texto
            String idJuga = jTidJugador.getText();
            String nombre = jTnombreJugador.getText();
            int edad = Integer.parseInt(jTedadJugador.getText());
            int rankinAtp = Integer.parseInt(jTrankingJugador.getText());

            //llamamos al contructor de jugador
            miJugador = new Jugador(idJuga, nombre, edad, rankinAtp);

            //llamamos el metodo agregar
            boolean agregarJuga = miOpenAustralia.agregarJugador(miJugador);

            //Mostramos mensaje de que se agrego o no el jugador
            if (agregarJuga) {
                imprimir("El Jugador se agrego");
            } else {
                imprimir("No se puede agregar el jugador");
            }

            //llamamos el metodo de la tabla para llenarla
            llenarTablaJugador();

            //ponemos en blanco los campo de textos
            jTidJugador.setText(null);
            jTnombreJugador.setText(null);
            jTedadJugador.setText(null);
            jTrankingJugador.setText(null);

            //se llama el metodo validar datos y se imprime en un joptionpane
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR!!! \n" + ValidarDatosAgregarJugador(), "Validando Datos",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jBagregarJugadorActionPerformed

    private void jTidJugadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTidJugadorKeyTyped
        // TODO add your handling code here:
        validarNumeros(jTidJugador, evt);
    }//GEN-LAST:event_jTidJugadorKeyTyped

    private void jTnombreJugadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnombreJugadorKeyTyped
        // TODO add your handling code here:
        validarLetras(jTnombreJugador, evt);
    }//GEN-LAST:event_jTnombreJugadorKeyTyped

    private void jTedadJugadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTedadJugadorKeyTyped
        // TODO add your handling code here:
        validarNumeros(jTedadJugador, evt);
    }//GEN-LAST:event_jTedadJugadorKeyTyped

    private void jTrankingJugadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTrankingJugadorKeyTyped
        // TODO add your handling code here:
        validarNumeros(jTrankingJugador, evt);
    }//GEN-LAST:event_jTrankingJugadorKeyTyped

    private void jBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarActionPerformed
        // TODO add your handling code here:
        int filSelec;
        int resp;
        String id;
        boolean eliminado;
        try {
            //selecciono una fila
            filSelec = jTableJugadores.getSelectedRow();
            //verifico si estoy seleccionando una fila
            if (filSelec == -1) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un item de la tabla", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                resp = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar este jugador?", "Eliminar", JOptionPane.YES_NO_OPTION);
                if (resp == JOptionPane.YES_OPTION) {
                    //obtengo el los datos de la columna 0
                    id = jTableJugadores.getValueAt(filSelec, 0).toString();
                    //llamo el metodo eliminar
                    eliminado = miOpenAustralia.eliminarJugador(id);

                    DefaultTableModel dtm = (DefaultTableModel) jTableJugadores.getModel();
                    dtm.removeRow(filSelec);

                    if (eliminado == true) {
                        imprimir("El jugador se elimino correctamente");
                    } else {
                        imprimir("Error!!! no se elimino");
                    }

                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jBborrarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarJugador(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregarJugador;
    private javax.swing.JButton jBborrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableJugadores;
    private javax.swing.JTextField jTedadJugador;
    private javax.swing.JTextField jTidJugador;
    private javax.swing.JTextField jTnombreJugador;
    private javax.swing.JTextField jTrankingJugador;
    // End of variables declaration//GEN-END:variables
    public static void imprimir(String msj) {
        JOptionPane.showMessageDialog(null, msj);
    }

    public void llenarTablaJugador() {
        DefaultTableModel dtm = (DefaultTableModel) jTableJugadores.getModel();//se usa DefaultTableModel para manipular facilmente el Tablemodel
        dtm.setRowCount(0);//eliminando la s filas que ya hay. para agregar desde el principio.
        //los datos se agregan la defaultTableModel.

        Jugador[] juga = miOpenAustralia.getJugadores();//sacando al informacion a agregar en la tabla.

        //como se va a llenar una tabla de 5 columnas, se crea un vector de 3 elementos.
        //se usa un arreglo de Object para poder agregar a la tabla cualquier tipo de datos.
        Object[] datos = new Object[5];

        for (int i = 0; i < juga.length; i++) {

            Jugador jugador = juga[i];
            //Se agrega este if para evitar que el extraiga datos en un campo null
            if (jugador != null) {

                datos[0] = jugador.getIdJugador();//el primer elemetno del arreglo va a ser el id,la primera col en la Tabla.
                datos[1] = jugador.getNombre();
                datos[2] = jugador.getEdad();
                datos[3] = jugador.getPuntosObtenidos();
                datos[4] = jugador.getRankinATP();

                //agrego al TableModleo ese arreglo
                dtm.addRow(datos);
            }
        }
        //metodo que modifica las celdas de la tabla
        dtm.addTableModelListener(new TableModelListener() {
            //metodo que verifica si existe un cambio en la tabla
            @Override
            public void tableChanged(TableModelEvent e) {
                //if que verifica si existe cambio
                if (e.getType() == TableModelEvent.UPDATE) {
                    //se obtiene la columna en la cual se modifico la celda
                    int columna = e.getColumn();
                    //se obtiene la dila en la cual se modifico la celda
                    int fila = e.getFirstRow();
                    //se obtiene el id del jugador de la fila seleccionada 
                    String id = jTableJugadores.getValueAt(fila, 0).toString();
                    //se obtiene el elemento modificado
                    String dato = jTableJugadores.getValueAt(fila, columna).toString();

                    miOpenAustralia.modificarJugador(id, dato, columna);
                }
            }
        });
        //**************************************************

    }
        public void validarNumeros(JTextField campo, KeyEvent evt) {
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "No puede ingresar letras!!!", "Validando Datos",
                    JOptionPane.INFORMATION_MESSAGE);
            campo.setCursor(null);
        } else if ((int) evt.getKeyChar() > 32 && (int) evt.getKeyChar() <= 47
                || (int) evt.getKeyChar() >= 58 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "No puede ingresar simbolos!!!", "Validando Datos",
                    JOptionPane.INFORMATION_MESSAGE);
            campo.setCursor(null);
        }
    }

    public void validarLetras(JTextField campo, KeyEvent evt) {
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "No puede ingresar numeros!!!", "Validando Datos",
                    JOptionPane.INFORMATION_MESSAGE);
            campo.setCursor(null);
        } else if ((int) evt.getKeyChar() > 32 && (int) evt.getKeyChar() <= 47
                || (int) evt.getKeyChar() >= 58 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "No puede ingresar simbolos!!!", "Validando Datos",
                    JOptionPane.INFORMATION_MESSAGE);
            campo.setCursor(null);
        }
    }

    public String ValidarDatosAgregarJugador() {//Metodo para comprobar que los datos esten completos
        String msj = "";
        if (jTidJugador.getText().equals("")) {//Si jTnombreCita esta vacio
            msj += "Por favor digite el Id. \n";
        }
        if (jTnombreJugador.getText().equals("")) {//Si jTidCita esta vacio
            msj += "Por favor digite el Nombre. \n";
        }
        if (jTedadJugador.getText().equals("")) {//Si jTidCita esta vacio
            msj += "Por favor digite la Edad. \n";
        }
        if (jTrankingJugador.getText().equals("")) {//Si jTidCita esta vacio
            msj += "Por favor digite el Ranking ATP. \n";
        }
        return msj;//devuelve msj
    }

}
