/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.*;
import logica.*;

/**
 *
 * @author Shonny & juank
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private OpenDeAustralia miOpenAustralia = new OpenDeAustralia();
    private Jugador miJugador;
    private Partido miPartido;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        //PONER EL FAVICON AL PROGRAMA
        setIconImage(new ImageIcon(getClass().getResource("/interfaz/images/logo.png")).getImage());
        //*********************************
        //inicializamos la persistencia del jugador
        try {
            miOpenAustralia.inicializarAtributosJugador();
            miOpenAustralia.inicializarAtributosPista();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "El archivo no pudo ser leído");
        }
        //*********************************

        //************************
        //Centrar Jframe
        setLocationRelativeTo(null);
        //************************
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMOctavos = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMCuartos = new javax.swing.JMenuItem();
        jMSemiFinal = new javax.swing.JMenuItem();
        jMFinal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Open de Australia");

        jMenu1.setText("Archivo");

        jMenu4.setText("Agregar");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Jugador");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Pista");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ver");

        jMOctavos.setText("Rondas");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Octavos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMOctavos.add(jMenuItem3);

        jMCuartos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMCuartos.setText("Cuartos");
        jMCuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCuartosActionPerformed(evt);
            }
        });
        jMOctavos.add(jMCuartos);

        jMSemiFinal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMSemiFinal.setText("Semi Final");
        jMSemiFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSemiFinalActionPerformed(evt);
            }
        });
        jMOctavos.add(jMSemiFinal);

        jMFinal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMFinal.setText("Final");
        jMFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMFinalActionPerformed(evt);
            }
        });
        jMOctavos.add(jMFinal);

        jMenu3.add(jMOctavos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        VentanaAgregarJugador agregarJugador = new VentanaAgregarJugador(miOpenAustralia);
        agregarJugador.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        VentanaAgregarPista pistas = new VentanaAgregarPista(miOpenAustralia);
        pistas.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        VentanaVerRondas rondas = new VentanaVerRondas(miOpenAustralia);
        int inicio = 0;
        int limite = 8;
        //se verifica si el arraylist esta vacio, si lo esta se agrega datos de lo contrario no se agrega nada
        if (miOpenAustralia.getPartidos().isEmpty()) {
            miOpenAustralia.generarOctavos();
        }

        rondas.llenarTabla(inicio, limite);
        rondas.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMCuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCuartosActionPerformed
        // TODO add your handling code here:
        VentanaVerRondas rondas = new VentanaVerRondas(miOpenAustralia);
        int tamArreglo;
        int inicioArray;
        int finalArray;

        int inicio = 8;
        int limite = 12;
        if (!(miOpenAustralia.getPartidos().isEmpty())) {
            if (miOpenAustralia.numeroGanadores() == 8 || miOpenAustralia.numeroGanadores() == 12 || miOpenAustralia.numeroGanadores() == 14 || miOpenAustralia.numeroGanadores() == 15) {
                if (miOpenAustralia.getPartidos().size() < 15) {
                    tamArreglo = 8;
                    inicioArray = 0;
                    finalArray = 8;

                    miOpenAustralia.generarPartidos(tamArreglo, inicioArray, finalArray);
                    rondas.llenarTabla(inicio, limite);
                    rondas.setVisible(true);
                } else {
                    rondas.llenarTabla(inicio, limite);
                    rondas.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Primero se tiene que jugar todos los octavos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Primero se tiene que jugar todos los octavos");
        }

    }//GEN-LAST:event_jMCuartosActionPerformed

    private void jMSemiFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSemiFinalActionPerformed
        // TODO add your handling code here:
        VentanaVerRondas rondas = new VentanaVerRondas(miOpenAustralia);
        int tamArreglo;
        int inicioArray;
        int finalArray;

        int inicio = 12;
        int limite = 14;
        if (!(miOpenAustralia.getPartidos().isEmpty())) {
            if (miOpenAustralia.numeroGanadores() == 12 || miOpenAustralia.numeroGanadores() == 14 || miOpenAustralia.numeroGanadores() == 15) {
                if (miOpenAustralia.getPartidos().size() < 15) {
                    tamArreglo = 4;
                    inicioArray = 8;
                    finalArray = 12;
                    miOpenAustralia.generarPartidos(tamArreglo, inicioArray, finalArray);
                    rondas.llenarTabla(inicio, limite);
                    rondas.setVisible(true);
                } else {
                    rondas.llenarTabla(inicio, limite);
                    rondas.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Primero se tiene que jugar todos los cuartos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Primero se tiene que jugar todos los cuartos");
        }
    }//GEN-LAST:event_jMSemiFinalActionPerformed

    private void jMFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMFinalActionPerformed
        // TODO add your handling code here:
        VentanaVerRondas rondas = new VentanaVerRondas(miOpenAustralia);
        int tamArreglo;
        int inicioArray;
        int finalArray;

        int inicio = 14;
        int limite = 15;
        if (!(miOpenAustralia.getPartidos().isEmpty())) {
            if (miOpenAustralia.numeroGanadores() == 14 || miOpenAustralia.numeroGanadores() == 15) {
                if (miOpenAustralia.getPartidos().size() < 15) {
                    tamArreglo = 2;
                    inicioArray = 12;
                    finalArray = 14;
                    miOpenAustralia.generarPartidos(tamArreglo, inicioArray, finalArray);
                    rondas.llenarTabla(inicio, limite);
                    rondas.setVisible(true);
                } else {
                    rondas.llenarTabla(inicio, limite);
                    rondas.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Primero se tiene que jugar todas las semi finales");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Primero se tiene que jugar todas las semi finales");
        }
    }//GEN-LAST:event_jMFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMCuartos;
    private javax.swing.JMenuItem jMFinal;
    private javax.swing.JMenu jMOctavos;
    private javax.swing.JMenuItem jMSemiFinal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables

}
